/**
 * Seed Data — 36 realistic IT helpdesk tickets for Priya's team.
 * Times are computed relative to the current real time at load so
 * the demo is always fresh regardless of when the app is opened.
 */

import { computeDeadline } from '../engine/slaManager.js';

const AGENTS = ['priya', 'alex', null];
const PRIYA = 'priya';
const ALEX = 'alex';

function ticket({ id, customer, email, company, subject, priority, status, assignee, createdMinsAgo, note }) {
  const createdAt = Date.now() - createdMinsAgo * 60 * 1000;
  const slaDeadline = computeDeadline(priority, createdAt);
  return {
    id,
    customer,
    email: email ?? `${customer.split(' ')[0].toLowerCase()}@${company.toLowerCase().replace(/\s+/g, '')}.com`,
    company,
    subject,
    priority,
    status: status ?? 'open',
    assignee: assignee ?? null,
    createdAt,
    slaDeadline,
    resolvedAt: status === 'resolved' ? createdAt + (Math.random() * 60 + 20) * 60 * 1000 : null,
    note: note ?? null,
    history: [],
  };
}

export const TEAM = [
  { id: 'priya', name: 'Priya Sharma', avatar: 'PS', color: '#7c3aed' },
  { id: 'alex',  name: 'Alex Chen',   avatar: 'AC', color: '#0ea5e9' },
];

export const seedTickets = [
  // ── CRITICAL / OVERDUE ─────────────────────────────────────────────────────
  ticket({
    id: 'TKT-0001',
    customer: 'Marcus Vance',
    company: 'Meridian Capital',
    subject: "Laptop won't boot — client demo starts in 20 minutes",
    priority: 'urgent',
    status: 'in_progress',
    assignee: PRIYA,
    createdMinsAgo: 135, // Created 2h 15m ago — well past 2h SLA
    note: 'Called Marcus directly. Trying Bitlocker recovery key.',
  }),
  ticket({
    id: 'TKT-0002',
    customer: 'Elena Rostova',
    company: 'NorthStar Sales',
    subject: 'VPN tunnel collapsed — entire remote sales team locked out',
    priority: 'urgent',
    status: 'open',
    assignee: null,
    createdMinsAgo: 145,
    note: null,
  }),
  ticket({
    id: 'TKT-0003',
    customer: 'David Kim',
    company: 'Pinnacle Finance',
    subject: 'SSO down for entire finance team during month-end close',
    priority: 'urgent',
    status: 'open',
    assignee: ALEX,
    createdMinsAgo: 130,
  }),
  ticket({
    id: 'TKT-0004',
    customer: 'Sophia Huang',
    company: 'BlueSky Media',
    subject: 'Exchange server not sending outbound emails — quotes bouncing',
    priority: 'high',
    status: 'open',
    assignee: null,
    createdMinsAgo: 260, // 4h 20m ago → overdue for high (4h SLA)
  }),
  ticket({
    id: 'TKT-0005',
    customer: 'Raj Patel',
    company: 'Vertex Consulting',
    subject: 'MFA app deleted — locked out of all corporate systems',
    priority: 'urgent',
    status: 'open',
    assignee: PRIYA,
    createdMinsAgo: 138,
  }),

  // ── APPROACHING / IMMINENT ──────────────────────────────────────────────────
  ticket({
    id: 'TKT-0006',
    customer: 'Liam Gallagher',
    company: 'Quantum Dynamics',
    subject: 'Zoom keeps crashing during all-hands — presenting in 1 hour',
    priority: 'urgent',
    status: 'open',
    assignee: ALEX,
    createdMinsAgo: 90,
  }),
  ticket({
    id: 'TKT-0007',
    customer: 'Aisha Okonkwo',
    company: 'Luminary Health',
    subject: 'Shared network drive unreachable from entire radiology wing',
    priority: 'high',
    status: 'in_progress',
    assignee: PRIYA,
    createdMinsAgo: 200,
  }),
  ticket({
    id: 'TKT-0008',
    customer: 'Carlos Mendes',
    company: 'Atlas Logistics',
    subject: 'Printer in warehouse not accepting jobs — 50 shipments stalled',
    priority: 'high',
    status: 'open',
    assignee: null,
    createdMinsAgo: 180,
  }),
  ticket({
    id: 'TKT-0009',
    customer: 'Grace O\'Sullivan',
    company: 'Ember Studios',
    subject: 'Adobe Creative Cloud license expired — design team can\'t work',
    priority: 'high',
    status: 'open',
    assignee: ALEX,
    createdMinsAgo: 170,
  }),
  ticket({
    id: 'TKT-0010',
    customer: 'James Whitfield',
    company: 'CoreEdge Tech',
    subject: 'GitHub Actions runner out of disk space — CI/CD pipeline blocked',
    priority: 'high',
    status: 'open',
    assignee: PRIYA,
    createdMinsAgo: 155,
  }),

  // ── NORMAL / HIGH — WITHIN SLA ─────────────────────────────────────────────
  ticket({
    id: 'TKT-0011',
    customer: 'Priscilla Nakamura',
    company: 'Horizon Bank',
    subject: 'New MacBook Pro won\'t connect to corporate Wi-Fi (802.1X)',
    priority: 'normal',
    status: 'open',
    assignee: null,
    createdMinsAgo: 60,
  }),
  ticket({
    id: 'TKT-0012',
    customer: 'Oliver King',
    company: 'Summit Analytics',
    subject: 'Slack keeps logging me out every 2 hours — very disruptive',
    priority: 'normal',
    status: 'in_progress',
    assignee: ALEX,
    createdMinsAgo: 45,
  }),
  ticket({
    id: 'TKT-0013',
    customer: 'Fatima Al-Rashid',
    company: 'Crescent Legal',
    subject: 'VPN connects but can\'t reach internal SharePoint sites',
    priority: 'normal',
    status: 'open',
    assignee: null,
    createdMinsAgo: 90,
  }),
  ticket({
    id: 'TKT-0014',
    customer: 'Noah Brandt',
    company: 'GreenWave Energy',
    subject: 'Excel crashing when opening files >50MB — data team blocked',
    priority: 'normal',
    status: 'open',
    assignee: PRIYA,
    createdMinsAgo: 30,
  }),
  ticket({
    id: 'TKT-0015',
    customer: 'Isabella Torres',
    company: 'Apex Realty',
    subject: 'OneDrive sync stuck — files from yesterday not synced',
    priority: 'normal',
    status: 'open',
    assignee: null,
    createdMinsAgo: 75,
  }),
  ticket({
    id: 'TKT-0016',
    customer: 'Ethan Blackwood',
    company: 'Ironclad Security',
    subject: 'Windows Update KB5034439 failing with error 0x800f0922',
    priority: 'normal',
    status: 'open',
    assignee: ALEX,
    createdMinsAgo: 120,
  }),
  ticket({
    id: 'TKT-0017',
    customer: 'Layla Hassan',
    company: 'SilverLeaf Pharma',
    subject: 'Outlook signature stripped when forwarding — compliance issue',
    priority: 'high',
    status: 'open',
    assignee: null,
    createdMinsAgo: 100,
  }),
  ticket({
    id: 'TKT-0018',
    customer: 'Felix Bauer',
    company: 'EuroTrade GmbH',
    subject: 'Webcam not detected in Webex — international call in 3 hours',
    priority: 'high',
    status: 'open',
    assignee: PRIYA,
    createdMinsAgo: 50,
  }),
  ticket({
    id: 'TKT-0019',
    customer: 'Yuki Tanaka',
    company: 'Fuji Digital',
    subject: 'PowerPoint presenter view not working on secondary display',
    priority: 'normal',
    status: 'open',
    assignee: null,
    createdMinsAgo: 110,
  }),
  ticket({
    id: 'TKT-0020',
    customer: 'Samuel Osei',
    company: 'AfriLink Telecom',
    subject: 'Can\'t install Python 3.12 — Windows says "system administrator"',
    priority: 'normal',
    status: 'open',
    assignee: ALEX,
    createdMinsAgo: 200,
  }),

  // ── LOW PRIORITY ────────────────────────────────────────────────────────────
  ticket({
    id: 'TKT-0021',
    customer: 'Chloe Bennett',
    company: 'Pixel Perfect Agency',
    subject: 'Requesting a larger secondary monitor for Figma design work',
    priority: 'low',
    status: 'open',
    assignee: null,
    createdMinsAgo: 300,
  }),
  ticket({
    id: 'TKT-0022',
    customer: 'Aaron Miller',
    company: 'DraftBit',
    subject: 'Access request to Figma Enterprise workspace for new joiners',
    priority: 'low',
    status: 'open',
    assignee: PRIYA,
    createdMinsAgo: 1440, // 24h old
  }),
  ticket({
    id: 'TKT-0023',
    customer: 'Mia Reynolds',
    company: 'CloudFirst Inc',
    subject: 'Wireless mouse scroll wheel making clicking noise — annoying',
    priority: 'low',
    status: 'open',
    assignee: null,
    createdMinsAgo: 720,
  }),
  ticket({
    id: 'TKT-0024',
    customer: 'Ben Ashworth',
    company: 'Sterling Group',
    subject: 'Keyboard repeat rate too fast — want to adjust sensitivity',
    priority: 'low',
    status: 'open',
    assignee: ALEX,
    createdMinsAgo: 480,
  }),
  ticket({
    id: 'TKT-0025',
    customer: 'Hana Kobayashi',
    company: 'Opal Ventures',
    subject: 'Dark mode not applying to Outlook calendar — aesthetic request',
    priority: 'low',
    status: 'open',
    assignee: null,
    createdMinsAgo: 360,
  }),
  ticket({
    id: 'TKT-0026',
    customer: 'Derek Stone',
    company: 'PrismTech',
    subject: 'Requesting a physical USB hub for the standing desk setup',
    priority: 'low',
    status: 'open',
    assignee: null,
    createdMinsAgo: 2880,
  }),
  ticket({
    id: 'TKT-0027',
    customer: 'Natalie Ford',
    company: 'BloomBox',
    subject: 'Teams background blurring not available on this machine',
    priority: 'low',
    status: 'open',
    assignee: PRIYA,
    createdMinsAgo: 600,
  }),

  // ── WAITING / PENDING ───────────────────────────────────────────────────────
  ticket({
    id: 'TKT-0028',
    customer: 'Chris Abara',
    company: 'MegaPort Shipping',
    subject: 'Label printer driver not compatible with Windows 11 upgrade',
    priority: 'high',
    status: 'waiting',
    assignee: ALEX,
    createdMinsAgo: 90,
    note: 'Awaiting vendor driver from Zebra — ETA tomorrow 9am.',
  }),
  ticket({
    id: 'TKT-0029',
    customer: 'Valeria Cruz',
    company: 'Solano Architecture',
    subject: 'AutoCAD license server returning "no licenses available"',
    priority: 'urgent',
    status: 'waiting',
    assignee: PRIYA,
    createdMinsAgo: 55,
    note: 'Escalated to Autodesk support — ticket #AUT-98123.',
  }),
  ticket({
    id: 'TKT-0030',
    customer: 'Patrick Nwosu',
    company: 'BrightPath NGO',
    subject: 'Salesforce integration failing with OAuth token expired error',
    priority: 'high',
    status: 'waiting',
    assignee: ALEX,
    createdMinsAgo: 240,
    note: 'Need Salesforce admin to re-authorize the connected app.',
  }),

  // ── RESOLVED ────────────────────────────────────────────────────────────────
  ticket({
    id: 'TKT-0031',
    customer: 'Sandra Lopez',
    company: 'Citadel Law',
    subject: 'Password reset for domain account after lockout',
    priority: 'urgent',
    status: 'resolved',
    assignee: PRIYA,
    createdMinsAgo: 500,
    note: 'Reset via AD, MFA re-enrolled. User confirmed working.',
  }),
  ticket({
    id: 'TKT-0032',
    customer: 'Tom Bradley',
    company: 'GlobeCast TV',
    subject: 'Teams audio feedback loop during live broadcast test',
    priority: 'high',
    status: 'resolved',
    assignee: ALEX,
    createdMinsAgo: 380,
    note: 'Fixed by changing audio device in Teams settings.',
  }),
  ticket({
    id: 'TKT-0033',
    customer: 'Amara Singh',
    company: 'NewGen Schools',
    subject: 'Google Classroom not loading on school-issued Chromebooks',
    priority: 'normal',
    status: 'resolved',
    assignee: PRIYA,
    createdMinsAgo: 1200,
    note: 'Cleared cache & refreshed Google policy via admin console.',
  }),
  ticket({
    id: 'TKT-0034',
    customer: 'Victor Cheng',
    company: 'AlphaWave Capital',
    subject: 'Bloomberg Terminal disconnected from market data feed',
    priority: 'urgent',
    status: 'resolved',
    assignee: ALEX,
    createdMinsAgo: 600,
    note: 'Bloomberg network service restarted. Feed restored in 8 mins.',
  }),
  ticket({
    id: 'TKT-0035',
    customer: 'Diana Müller',
    company: 'Heidelberg Systems',
    subject: 'Dual-monitor not detected after Windows 11 23H2 update',
    priority: 'normal',
    status: 'resolved',
    assignee: PRIYA,
    createdMinsAgo: 2000,
    note: 'Rolled back display driver to 31.0.101.2115. Issue resolved.',
  }),
  ticket({
    id: 'TKT-0036',
    customer: 'Leo Fontaine',
    company: 'Maison Digital',
    subject: 'Can\'t share screen in Google Meet — extension blocked by policy',
    priority: 'normal',
    status: 'resolved',
    assignee: ALEX,
    createdMinsAgo: 800,
    note: 'Allowed screen capture extension via Workspace Admin.',
  }),
];
